-- ==============================
-- LIMPEZA DAS TABELAS (para ambiente de desenvolvimento)
-- ==============================
DROP TABLE IF EXISTS locacao_equipamento;
DROP TABLE IF EXISTS pagamentos;
DROP TABLE IF EXISTS locacoes;
DROP TABLE IF EXISTS equipamentos;
DROP TABLE IF EXISTS clientes CASCADE;

-- ==============================
-- CLIENTES
-- ==============================
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    email VARCHAR(100),
    cep VARCHAR(10),
    logradouro VARCHAR(100),
    numero VARCHAR(10),
    complemento VARCHAR(50),
    bairro VARCHAR(50),
    cidade VARCHAR(50),
    estado VARCHAR(2)
);

-- ==============================
-- EQUIPAMENTOS
-- ==============================
CREATE TABLE equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    valor_diaria DECIMAL(10,2) NOT NULL,
    disponivel BOOLEAN DEFAULT TRUE
);

-- ==============================
-- LOCAÇÕES
-- ==============================
CREATE TABLE locacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    dias INT NOT NULL,
    valor_total DECIMAL(10,2),
    devolvido BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);

-- ==============================
-- LOCAÇÃO_EQUIPAMENTO (tabela de relação N:N)
-- ==============================
CREATE TABLE locacao_equipamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locacao_id BIGINT NOT NULL,
    equipamento_id BIGINT NOT NULL,
    quantidade INT NOT NULL DEFAULT 1,
    valor_unitario DECIMAL(10,2) NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (locacao_id) REFERENCES locacoes(id) ON DELETE CASCADE,
    FOREIGN KEY (equipamento_id) REFERENCES equipamentos(id)
);

-- ==============================
-- PAGAMENTOS
-- ==============================
CREATE TABLE pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locacao_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('PIX', 'BOLETO', 'CARTAO')),
    valor DECIMAL(10,2) NOT NULL,
    referencia VARCHAR(100),
    data_pagamento TIMESTAMP,
    FOREIGN KEY (locacao_id) REFERENCES locacoes(id) ON DELETE CASCADE
);

-- ==============================
-- ÍNDICES
-- ==============================
CREATE INDEX idx_equip_disponivel ON equipamentos(disponivel);
CREATE INDEX idx_locacao_cliente ON locacoes(cliente_id);
CREATE INDEX idx_pagamento_tipo ON pagamentos(tipo);
CREATE INDEX idx_locacao_equipamento_locacao ON locacao_equipamento(locacao_id);
CREATE INDEX idx_locacao_equipamento_equipamento ON locacao_equipamento(equipamento_id);
